### ISSUE TITLE
Bug in ancestral state reconstruction

### ISSUE THREAD

**Issue by trvrb** [stamatak/standard-RAxML#18]
I've just discovered a bug in ancestral state reconstruction (`-f A`) in the latest source (53e5f1887185ac695995b69bd0cd3494ce212cc7).

This bug occurs when sister tips in the tree have gaps in their sequences. In this [example](https://dl.dropboxusercontent.com/u/1377267/raxml-fail.zip), I have [`temp.phyx`](https://dl.dropboxusercontent.com/u/1377267/raxml-fail/temp.phyx) which contains 5 sequences, 2 of which (A/SHIMANE/194/2011 and A/KUMAMOTO-C/36/2011) have gaps at their beginnings. I also have [`temp.newick`](https://dl.dropboxusercontent.com/u/1377267/raxml-fail/temp.newick) which contains a tree connecting these taxa.

If I run:

```
raxml -f A -T 6 -s temp.phyx -n states -c 25 -m GTRGAMMA -p 344312987 -t temp.newick
```

I get a failure of RAxML to reconstruct the states of the parent of SHIMANE and KUMAMOTO as is seen in [`RAxML_marginalAncestralStates.states`](https://dl.dropboxusercontent.com/u/1377267/raxml-fail/RAxML_marginalAncestralStates.states), where:

```
6 ????????????????????????????????????????????????CAAAAACT...
8 ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAAAACT...
7 ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAAAACT...
ROOT ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAAA...
```

Looking at the probabilities file, these nodes are listed as (0.25,0.25,0.25,0.25).

---------------------

However, if I use only one of these gapped sequences, everything works just fine. In this [example](https://dl.dropboxusercontent.com/u/1377267/raxml-success.zip), I have 4 sequences in [`temp.newick`](https://dl.dropboxusercontent.com/u/1377267/raxml-success/temp.newick) / [`temp.phyx`](https://dl.dropboxusercontent.com/u/1377267/raxml-success/temp.phyx), keeping SHIMANE and dropping KUMAMOTO.

Running the same command as above gives output in [`RAxML_marginalAncestralStates.states`](https://dl.dropboxusercontent.com/u/1377267/raxml-success/RAxML_marginalAncestralStates.states), where:

```
5 ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAAAAC...
6 ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAAAAC...
ROOT ATGAAGACTATCATTGCTTTGAGCTACATTCTATGTCTGGTTTTCGCTCAAA...
```

---------------------

Please let me know if you have any questions. Thanks for looking into this!

**Comment by trvrb** [comment]
I've posted this to the RAxML Google Group as well: https://groups.google.com/d/msg/raxml/ohnH773kXuY/N9emhJSkaJIJ

**Comment by stamatak** [comment]
This was not a bug, but a misunderstanding about how marginal ancestral states are calculated in RAxML. See corresponding discussion in the RAxML google group.

Alexis
