### ISSUE TITLE
Allow hypothesis testing with the SH-like test

### ISSUE THREAD

**Issue by josephwb** [stamatak/standard-RAxML#19]
As currently implemented, the SH-like test requires the tree being tested to be NNI optimal, and will actually find a better tree if possible. However, this does not allow for targeted hypothesis testing, say, for testing alternative (suboptimal) resolutions. I think either 1) removing the search for a better NNI tree or 2) adding an argument for turning this off would make the test far more useful.

Thanks!

**Comment by blackrim** [comment]
I will add that I agree with @josephwb that the hypothesis testing would be helpful. However, I think losing the NNI search option would be suboptimal because on large trees, this search after a full ML often produces significantly better trees.

**Comment by josephwb** [comment]
Good point. I see this as two separate goals. So this aligns with the option 2 above: giving the user the ability to turn it off when appropriate.

**Comment by stamatak** [comment]
I'll try to implement that, but I will be on vacations until September 
6, so it might take some time.

Alexis

On 17.08.2015 17:04, Joseph W. Brown wrote:
> Good point. I see this as two separate goals. So this aligns with the
> option 2 above: giving the user the ability to turn it off when appropriate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamatak/standard-RAxML/issues/19#issuecomment-131855509>.
>

-- 
Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org

**Comment by stamatak** [comment]
Hi Jospeh again,

I'd prefer you to post this stuff in the raxml google group please, like 
this also somebody else can answer while I am away and all raxml issues 
are in on eplace.

thanks,

alexis

On 17.08.2015 17:04, Joseph W. Brown wrote:
> Good point. I see this as two separate goals. So this aligns with the
> option 2 above: giving the user the ability to turn it off when appropriate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamatak/standard-RAxML/issues/19#issuecomment-131855509>.
>

-- 
Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org

**Comment by josephwb** [comment]
Will do. Thanks.

**Comment by josephwb** [comment]
Closing here since it has been posted to google group.
