### ISSUE TITLE
different likelihoods with -f N under different scenarios and as compared to -f a

### ISSUE THREAD

**Issue by blackrim** [stamatak/standard-RAxML#20]
I have an example with a very small alignment (see below) where I want the likelihood for three alternative topologies (see below). All of this is using the most recent pull from github (Standard RAxML version 8.2.3). The alignment is just
```
4 28
L1	ACGTACGTACGTAAAAACGTAAAAAAAA
R1	ACGTACGTAAAAAAAAAAAAACGTAAAA
R2	ACGTACGTAAAAAAAAAAAAACGTAAAA
L2	ACGTAAAAAAAAAAAAAAAAAAAAACGT
```
The ML tree should be `((L1,L2),R1,R2)` and this is what is found with the command 
`raxml -f a -# 100 -p 12345 -x12345 -s test.fa -n FA -m GTRGAMMA ` with the final ML likelihood
`Final ML Optimization Likelihood: -71.683849`

When I run `raxml -s test.fa -n tall -m GTRGAMMA -T 2 -p 123 -f N -z test.trees`
with the test.trees file of 
```
(L1,L2,(R1,R2));
(L1,R1,(L2,R2));
(L1,R2,(L2,R1));
``` 
I get the likelihoods 
```
Tree 0 Likelihood -71.683849 Tree-Length 1.502389
Tree 1 Likelihood -71.659851 Tree-Length 1.399745
Tree 2 Likelihood -71.640813 Tree-Length 1.319418
```
with the Tree 0 as the worst. This doesn't make sense given the alignment or the ML analysis (and support of 100 for that L1,L2 | R1,R2 split.

If I split out each of the trees from the set above into individual files and run each separately like
```
raxml -s test.fa -n t0 -m GTRGAMMA -T 2 -p 123 -f N -z test.trees.0 
raxml -s test.fa -n t1 -m GTRGAMMA -T 2 -p 123 -f N -z test.trees.1 
raxml -s test.fa -n t2 -m GTRGAMMA -T 2 -p 123 -f N -z test.trees.2
```
I get 
```
Tree 0: -71.683849
Tree 1: -71.683884
Tree 2: -71.683884
```
This is more sensible. However, this creates quite the unnecessary I/O burden.  So something seems to be up with the `-f N` option with multiple trees.

**Comment by blackrim** [comment]
discovered that in general, -f N is not quite getting the right answers even when doing them in separate files. hm

**Comment by stamatak** [comment]
hi stephen,

can you please post this in the google group,

this is of more general interest,

alexis

On 17.08.2015 21:06, Stephen Smith wrote:
> discovered that in general, -f N is not quite getting the right answers
> even when doing them in separate files. hm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamatak/standard-RAxML/issues/20#issuecomment-131931917>.
>

-- 
Alexandros (Alexis) Stamatakis

Research Group Leader, Heidelberg Institute for Theoretical Studies
Full Professor, Dept. of Informatics, Karlsruhe Institute of Technology
Adjunct Professor, Dept. of Ecology and Evolutionary Biology, University
of Arizona at Tucson

www.exelixis-lab.org

**Comment by blackrim** [comment]
done, will close here
