### ISSUE TITLE
Negative time duration for bootstraps and/or total time on Windows versions 

### ISSUE THREAD

**Issue by hrabe** [stamatak/standard-RAxML#23]
There seems to be a calculation issue for time duration's that gets written to console output either by few of the bootstrap iterations or worst case the total run-time. This happens only, if Windows version will be used.

**Comment by stamatak** [comment]
That's a know problem, please let me know which of the solutions here:

http://stackoverflow.com/questions/10905892/equivalent-of-gettimeday-for-windows

works best and I will integrate it.

**Comment by hrabe** [comment]
The working version is already pending and tested with several Windows Versions and compilers.
Please see the diff inside the pull request pending for each issue I've created.
