### ISSUE TITLE
Missing .gitignore file to specify files intentionally not to be tracked

### ISSUE THREAD

**Issue by hrabe** [stamatak/standard-RAxML#27]
Running a compile produces a lot of intermediate file `*.o` and executables `raxmlHPC*` that must not be tracked at the source control system.

This can be avoided using a `.gitignore` file and guards against accidentally commit of intermediate/unwanted files.

**Comment by stamatak** [comment]
Thanks, but I have never encountered difficulties doing this without a gitignore so I will leave it as is.
