### ISSUE TITLE
Core dumped when adding bipartition information to a tree

### ISSUE THREAD

**Issue by jgerken** [stamatak/standard-RAxML#32]
I have calculated a tree using the following command (the alignment was checked previously):

```
raxmlHPC-PTHREADS-AVX2 -D -f D -F -j -m GTRCAT -n NAME -O -p 28759 -s alignment.fasta -T 4 --silent --no-seq-check
```

than I ran the following command to add the RELL bootstrap information to the result tree:

```
raxmlHPC-PTHREADS-AVX2 -f b -j -m GTRCAT -n NAME-BS -t RAxML_result.NAME -T 4 -z RAxML_rellBootstrap.NAME
```

This command fails with the following message:

```
raxmlHPC-PTHREADS-AVX2: treeIO.c:1397: treeReadLen: Assertion `0' failed.
/var/spool/gridengine/execd/mg9/job_scripts/645420: line 21: 24614 Aborted                 (core dumped) "${RAXML}" ${PARAMS} $1
```

Since I skipped the GAMMA optimization and did not run the `-f e` command (would have been run with GTRCAT, too) my tree has no branch lengths yet. Could that be the problem? It would be great if RAxML gives an error message pointing to the problem.

I have the core file (29G) and the tree files (4.9M and 4.8G) but I cannot attach them here due to their size (the tree has 279,954 sequences/taxa). Send me a message if you need them for debugging, I will then setup a download option for you.

**Comment by jgerken** [comment]
I forgot to add: I have used RAxML v8.2.4.

**Comment by jgerken** [comment]
Now further calculations has finished and I can confirm when running the `-f e`command prior to the `-f b`, the tree containing the bi-partition information is created successfully. Thus, the easiest solution will likely be to insert a check for the presence of the branch lengths, giving an appropriate error message if they are missing and add the prerequisite to the manual. 

However, I do not unterstand why adding the bi-partition information to the tree requires the branch lengths. In my opinion, both operations are complete unrelated.

**Comment by stamatak** [comment]
Please re-post this bug report on the raxml google group. It makes it easier for me if everything is just in one place.

**Comment by stamatak** [comment]
The error message you want was already there in v 8.2.7 I made it even a bit more verbose:

RAxML was called as follows:

./raxmlHPC-AVX -f b -m GTRCAT -t RAxML_parsimonyTree.T2 -z RAxML_bootstrap.T3 -n t7 




Found 1 tree in File RAxML_parsimonyTree.T2



Found 10 trees in File RAxML_bootstrap.T3



Found 1 tree in File RAxML_parsimonyTree.T2

ERROR: Expecting ':' in tree; found: character ','

((Loach,(Frog,(Human,Carp))),(Seal,(Chic
                    ^

RAxML may be expecting to read a tree that contains branch lengths

ERROR: problem reading branch length ... RAxML will abort with a failing assertion

raxmlHPC-AVX: treeIO.c:1409: treeReadLen: Assertion `0' failed.
Aborted (core dumped)
