### ISSUE TITLE
epa slow and fast placement algorithms

### ISSUE THREAD

**Issue by GuangchuangYu** [stamatak/standard-RAxML#37]
I notice that epa has two algorithms for placement, <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3078422/>, but can't found any document for it.

Can you kindly tell me which parameter can switch from these two algorithms?

Thanks,
Guangchuang

**Comment by stamatak** [comment]
Please use the raxml google group for user questions, thank you :-) 

alexis
