### ISSUE TITLE
Assertion error when using single-threaded AVX

### ISSUE THREAD

**Issue by mbakke** [stamatak/standard-RAxML#39]
Hi,

I discovered this problem when running the test suite of another program which defaults to the AVX version (when available).

    raxmlHPC-AVX: optimizeModel.c:123: setRateModel: Assertion `rate >= RATE_MIN && rate <= RATE_MAX' failed.

I can't reproduce this with PTHREADS-AVX, -SSE3 or the unoptimized version.

The full command is:

    raxmlHPC-AVX -f d -p 1 -m GTRCAT -V -s /tmp/guix-build-python-gubbins-2.1.0.drv-0/gubbins-2.1.0/python/RAxML_result.multiple_recombinations.iteration_2.phylip -n multiple_recombinations.iteration_3 -t /tmp/guix-build-python-gubbins-2.1.0.drv-0/gubbins-2.1.0/python/RAxML_result.multiple_recombinations.iteration_2

The two test files are available here: https://github.com/mbakke/raxml-test

**Comment by stamatak** [comment]
as a quick fix specify: --no-bfgs in the command line

**Comment by stamatak** [comment]
This now also works of  --no-bfgs is NOT specified, check my latest commit.
