### ISSUE TITLE
axml.h file

### ISSUE THREAD

**Issue by giriarteS** [stamatak/standard-RAxML#41]
I installed raxml with homebrew on a mac. When I tried to run raxml I got the following error:
raxmlHPC-PTHREADS -m GTRGAMMAI -p 12345 -# 20 -s align.phy -n T13 -T 20
Taxon Name too long at taxon 1, adapt constant nmlngth in
axml.h, current setting 256

I found the axml.h file but this file belong to a local installation of one of the computer users (he followed your instructions on this page). So, I modified the axml.h on the local folder and tried to run raxml again from there but i got the same error. Any suggestions?

**Comment by stamatak** [comment]
Would you mind posting your question again on the raxml google group, I will reply there,

Alexis
