### ISSUE TITLE
No tree file output

### ISSUE THREAD

**Issue by whynotlih** [stamatak/standard-RAxML#45]
Hi!
I try to construct tree by the **RAxML-HPC2 on XSEDE on the CIPRES protal**, but there was no tree file output when it finished. What's wrong with me? Thanks!

The commind i used:
Executing 100 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA+P-Invar model of rate heterogeneity, ML estimate of alpha-parameter

GAMMA+P-Invar Model parameters will be estimated up to an accuracy of 0.0010000000 Log Likelihood units

Partition: 0
Alignment Patterns: 4465
Name: No Name Provided
DataType: AA
Substitution Matrix: LG
Using empirical base frequencies

RAxML was called as follows:

raxmlHPC-HYBRID -T 4 -n result -s infile.txt -p 12345 -m PROTGAMMAILGF -f a -N 100 -x 12345

**Comment by lczech** [comment]
Hi @whynotlih,

please use our [RAxML Google Group](https://groups.google.com/forum/?hl=de&fromgroups#!forum/raxml) for questions like this.

Thanks
Lucas

**Comment by whynotlih** [comment]
I'm sorry！But Google is inconvenient due to Great Firewall.  I'll have a try, thanks.
在 2017-11-17 22:54:46，"Lucas Czech" <notifications@github.com> 写道：
