### ISSUE TITLE
how to generate a binary tree?

### ISSUE THREAD

**Issue by haojingshao** [stamatak/standard-RAxML#47]
Dear RAxML developer,

I am using RAxML to generate a tree. Then I submit the RAxML tree result to another software named "CAFE". The result is something like "(A,(...),B);". The software "CAFE" says the tree is not binary. Do you know how can I convert or generate a binary tree? Do I need to specify a outgroup? 

Thanks,
Haojing

**Comment by stamatak** [comment]
By default the trees generated by RAxML are binary, maybe the input tree also needs to be rooted? In that case you would use an outgroup. In general, please ppost such questions on the raxxml google group please.
