### ISSUE TITLE
How to set the model parameter for GTR+F+I?

### ISSUE THREAD

**Issue by liufuyan2016** [stamatak/standard-RAxML#48]
I use IQ-TREE for model test, and the optional model is GTR +F+I. Could you help me how to set the model in RaxML.

**Comment by stamatak** [comment]
A coule of things: 

1. Please read the RAxML manual at: https://cme.h-its.org/exelixis/resource/download/NewManual.pdf
2. Please use the RAxML google group for such questions 
3. Please upgrade to RAxML-NG: https://github.com/amkozlov/raxml-ng

**Comment by liufuyan2016** [comment]
Thanks. In my opinion, I should use GTRCATXI . This is right?
