### ISSUE TITLE
Kappa calculation from RAxML output.

### ISSUE THREAD

**Issue by mmaesaar** [stamatak/standard-RAxML#49]
Could you explain is it possible to calculate kappa (transition transversion rate ratio)?

```
Tree-Length: 0.028897
rate A <-> C: 2.239533
rate A <-> G: 13.062129
rate A <-> T: 1.119423
rate C <-> G: 1.770590
rate C <-> T: 22.210862
rate G <-> T: 1.000000

freq pi(A): 0.358581
freq pi(C): 0.130893
freq pi(G): 0.185799
freq pi(T): 0.324727
```

Is it calculated as follows:
> kappa = (13.062129+22.210862)/(2.239533+1.119423+1.770590+1.000000) = 35,272991/6,129546 = 5,7545845973

PS! I also posted this issue to ClonalFrameML github, but it seemed better to post it here.

Thanks.

**Comment by stamatak** [comment]
Would you mind posting this question on the RAxML google group? We will answer it there. 

Thank you,

Alexis
