### ISSUE TITLE
redundancy in genetic distance output

### ISSUE THREAD

**Issue by boristim66** [stamatak/standard-RAxML#51]
This is just a petty suitor to a wonderful program, but it is misleading. The accuracy of storing a real number of the double type is 14-15 decimal digits, so printing the distance (getBranchLength) in the format  % 8.20f  is not valid, , since it introduces garbage into the output

**Comment by stamatak** [comment]
Sorry that I never replied to this, indeed you are right, but standard RAxML is not being maintained any more for quite some time now.
