### ISSUE TITLE
Packaging RAxML

### ISSUE THREAD

**Issue by V-Z** [stamatak/standard-RAxML#54]
Not really an issue, I just inform that I package RAxML for openSUSE GNU/Linux:

- https://software.opensuse.org/package/RAxML
- https://build.opensuse.org/package/show/home:vojtaeus/RAxML

I hope to submit the packages soon into [scientific repository](https://build.opensuse.org/project/show/science).

**Comment by stamatak** [comment]
Many thanks for the info. I hope that you are aware that standard RAxML is not being maintained any more (still being used though) since we have released RAxML-NG: https://github.com/amkozlov/raxml-ng

**Comment by V-Z** [comment]
I know RAxML is not maintained anymore (but still used, indeed). I did not know about RAxML-NG. Thank You for letting me know. I also packaged it :-)

- https://software.opensuse.org/package/RAxML-NG
- https://build.opensuse.org/package/show/home:vojtaeus/RAxML-NG

I packaged the version with MPI support. If packaging without MPI, I'd have to create extra package, and I doubt this is really needed...

I also packaged ExaML:

- https://software.opensuse.org/package/ExaML
- https://build.opensuse.org/package/show/home:vojtaeus/ExaML

Testing on my computer works well. Unfortunately, it's not straightforward to package MPI applications also for another Linux distributions than openSUSE, but on binary level the packages could work well. Also, right now, I don't care much about another architectures than x86_64. Anyway, I hope it helps someone. :-) Of course, when there is new version, I'll update.

**Comment by stamatak** [comment]
Thank you so much :-) just a comment on the MPI packaging: my impression has always been that RAxML(-NG) is predominantly used in the sequential and multi-threaded flavor (90% of the users I'd say), so it would be worthwhile packing this as well.

**Comment by V-Z** [comment]
OK, package [RAxML-NG-MPI](https://software.opensuse.org/package/RAxML-NG-MPI) contains version with MPI, package [RAxML-NG](https://software.opensuse.org/package/RAxML-NG) without MPI. [ExaML](https://software.opensuse.org/package/ExaML) is MPI-only, isn't it? And package [RAxML](https://software.opensuse.org/package/RAxML) contains all binaries - if needed, it could be split.

**Comment by stamatak** [comment]
Yes, ExaML is MPI-only, the rest seems to be complete, thanks a lot :-)
