### ISSUE TITLE
Exit code 0 thrown albeit error in ancestral state reconstruction

### ISSUE THREAD

**Issue by jtklein** [stamatak/standard-RAxML#56]
When performing an ancestral state reconstruction analysis, e.g.
`raxmlHPC -f A -t ...` with an unrooted tree, raxml throws an error when aborting "Error: The ancestral state computation mode requires a rooted tree as input, exiting ....". However, the binary exits with exit code 0, signaling success.

I would expect an exit code of -1 after this error.

**Comment by stamatak** [comment]
Thank you for this. standard-RAxML is not maintained any more, please use RAxML-NG: https://github.com/amkozlov/raxml-ng which also has a better ancestral state computation mode.
