### ISSUE TITLE
RAxML can't, parse the alignment file as phylip file

### ISSUE THREAD

**Issue by Jun666Yang** [stamatak/standard-RAxML#61]
Dear author:
         when I run standard-RAxML-8.2.12, have a problem
          【RAxML can't, parse the alignment file as phylip file 
          it will now try to parse it as FASTA file】
could you help me , thank you

**Comment by stamatak** [comment]
Please post your question on the RAxML google group, thank you.

**Comment by Jun666Yang** [comment]
> Please post your question on the RAxML google group, thank you.

ok , I have posted it on the RAxML google group
