### ISSUE TITLE
problems with memory

### ISSUE THREAD

**Issue by pavlo888** [stamatak/standard-RAxML#62]
Hi, 

I have been trying to calculate the bootstrap for a phylogeny of ~200 bacterial genomes. However, I cannot manage to obtain any results. So far, I have tried it three times using the following commands:

raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n tree_w_bootstraps -f a -m GTRCAT -# 100 -p 1989 -x 1989 T 8
raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n tree_w_bootstraps2 -f a -m GTRCAT -# 100 -p 1989 -x 1989 T 4
raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n tree_w_50b00tstraps -f a -m GTRCAT -N 10 -p 1989 -x 1989 T 2

I eventually get the following error message:

zsh: killed raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n -f a -m GTRCA
zsh: killed raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n -f a -m GTRCA
zsh: killed raxmlHPC-PTHREADS-SSE3 -s Agro_tax_217_fna_concatenated.aln -n -f a -m GTRCA

When I ran the command the first time, the procedure finished all 100 bootstrapping and was on the Fast ML tree optimisation. The second time I ran the command, the procedure was on the 51st bootstrapping.

I assume that the problem has to do with the memory, but I am not sure how to fix it exactly. Is there an option that could help with memory use? I am running the package in a laptop MacBook Air (processor: 1,6 GHz Dual-Core Intel Core i5, and memory: 8 GB 1600 MHz DDR3) and I am using an external disk for storing the output files.

Thank you for your help!

Cheers,
Pablo

**Comment by stamatak** [comment]
Please re-post your question on the RAxML google group, we will answer it there.
