### ISSUE TITLE
Why Raxml is taking too long to prepare a tree 

### ISSUE THREAD

**Issue by krishna1925** [stamatak/standard-RAxML#63]
Dear Alexis,  
Good Morning!  
 
I used raxmlHPC command for my alignment and it took me more than a month to align my 1.4 Mb genomic sequences of 779 isolates. So, I looked for a quicker way to generate raxml tree and I could see that raxmlHPC-PTHREADS-SSE3 is substantially faster. I submitted my alignment to the server with a total core of 16 cores and assigned 12 threads for my analysis. So, could you please kindly tell me how long it will take to get ML tree using this command?  Will it be ready within a week?

 
 
raxmlHPC-PTHREADS-SSE3 -s Suberis_lcb_masked.fasta -m GTRGAMMA -f a -p 12345 -x 12345 -T 12 -N 1000 -n raxml_prasnp_concatenated_LCB_1055sites_masked_100boot. 

 
Could you please let me know if there are any other alternatives to quickly prepare ML tree using raxml? 
 
Thank you.

**Comment by stamatak** [comment]
Please use RAxML-NG and/or post to the RAxML google group for support.
