### ISSUE TITLE
likelihood failed

### ISSUE THREAD

**Issue by Lcornet** [stamatak/standard-RAxML#67]
I have an error with some of my datasets with RaxML (fast mode) when I am running my jackknife : 

 raxmlHPC-PTHREADS-AVX: fastSearch.c:1290: fastSearch: Assertion `tr->likelihood >= likelihood' failed.
  .command.sh: line 7: 2795229 Aborted                 (core dumped) raxmlHPC-PTHREADS-AVX -T 20 -s $f.phy -n $f-RAXML-PROTGAMMALGF-fast -m PROTGAMMALGF -p 197502170357$

Is it because the organisms are very close ?

Thanks for the help

**Comment by stamatak** [comment]
standard RAxML is not supported any more, please switch to RAxML-NG: https://github.com/amkozlov/raxml-ng
