### ISSUE TITLE
problem about  the number of expected states is 20 the number of states that are present is 19.

### ISSUE THREAD

**Issue by jianshu93** [stamatak/standard-RAxML#73]
Dear raxml team,

the newest version 8.2 or later, for multiple trimmed alignments with corresponding partition file, I always have this error:

 the number of expected states is 20 the number of states that are present is 19. then the segment fault is encountered. 

iqtree2 solve this problem by doing this without error:

WARNING: Normalizing state frequencies so that sum of them equals to 1, can we also did this in RAxML?
 
code is this:

raxmlHPC-PTHREADS -f a -m GTRGAMMA -p 740281 -q full_alignment.concat.partition -s full_alignment.concat.fa -w~/data/ -n SAR11_SAG_bcgtree_final -T 4 -x 28840 -N 100

[Archive.zip](https://github.com/stamatak/standard-RAxML/files/13833710/Archive.zip)

How can I get rid of this error, the trimmed alignment is the problem I think.

Thanks,

Jianshu

**Comment by stamatak** [comment]
Dear @jianshu93 could you please re-post this question on the RAxML google group? We will answer it there. Thank you, Alexis
