### ISSUE TITLE
ERROR: Sequences out of alignment

### ISSUE THREAD

**Issue by ShanfenO** [stamatak/standard-RAxML#74]
Dear RAxML developer,
       When I use this command：
       "raxmlHPC -m GTRGAMMA -t modified_tree.newick -s TAS1R1.align.mafft.trimal.cds.afa.genome.phylip.species.delete -n TAS1R1"
        The error I encountered is:
"ERROR: Sequences out of alignment
1131 (instead of 1356) residues read in sequence 163 Horornis_vulcanius
Printing error context:

-------------------
Hydrobates_tethys --

Problem reading alignment file
"

The two files mentioned in the command line are attached. Please remove the ".txt" suffix before using them.

[TAS1R1.align.mafft.trimal.cds.afa.genome.phylip.species.delete.txt](https://github.com/stamatak/standard-RAxML/files/14434790/TAS1R1.align.mafft.trimal.cds.afa.genome.phylip.species.delete.txt)
[modified_tree.newick.txt](https://github.com/stamatak/standard-RAxML/files/14434791/modified_tree.newick.txt)

Thanks,
Sum

**Comment by stamatak** [comment]
The sequences are not aligned properly, they have different lengths.
